requires 'CGI';
requires 'Class::Accessor';
requires 'Crypt::JWT';
requires 'Data::Structure::Util';
requires 'DBI';
requires 'DateTime';
requires 'Future::AsyncAwait', '0.52';
requires 'JSON::XS';
requires 'Locale::Maketext::Lexicon';
requires 'Math::Random::Secure';
requires 'Mojolicious';
requires 'Proc::ProcessTable';
requires 'String::ShellQuote';
requires 'Test::Mojo';
requires 'Test::More';
requires 'GD';
requires 'Tie::IxHash';
requires 'TimeDate';             # Date::Format
requires 'UUID::Tiny';
requires 'YAML::XS';
