#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";
use lib "$FindBin::Bin/../lib/PG";
use lib "$FindBin::Bin/../lib/PG/lib";
use lib "$FindBin::Bin/../lib/WeBWorK";
use Mojo::File 'curfile';
use Mojolicious::Commands;

# Start command line interface for application
Mojolicious::Commands->start_app('RenderApp');
